<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Tuesday, December 12, 2023 3:54:19 PM</msg><msg code="0" type="0">Float(Raster(r"C:\Users\sadie\OneDrive\Documents\Lab Pratical\LabPractical_DATA\ir_rband") - Raster(r"C:\Users\sadie\OneDrive\Documents\Lab Pratical\LabPractical_DATA\color_rband")) / Float(Raster(r"C:\Users\sadie\OneDrive\Documents\Lab Pratical\LabPractical_DATA\ir_rband") + Raster(r"C:\Users\sadie\OneDrive\Documents\Lab Pratical\LabPractical_DATA\color_rband"))</msg><msg code="539" type="100">ERROR 000539: Traceback (most recent call last):
  File "&lt;expression&gt;", line 1, in &lt;module&gt;
  File "&lt;string&gt;", line 5, in rcexec_DC684390_0C54_4F14_9EBF_B34DF3F2E1B1
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\sa\Raster.py", line 79, in __new__
    return super().__new__(cls, in_raster, is_multidimensional)
RuntimeError: ERROR 000732: Input Raster: Dataset C:\Users\sadie\OneDrive\Documents\Lab Pratical\LabPractical_DATA\ir_rband does not exist or is not supported
</msg><msg code="-2147467259" type="100">Failed to execute (RasterCalculator).</msg><msg code="0" type="3">Failed at Tuesday, December 12, 2023 3:54:19 PM (Elapsed Time: 0.42 seconds)</msg></messages>